name: spacenet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9

  # core python stack
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - h5py
  - tifffile

  # notebooks
  - jupyterlab

  # geospatial
  - geopandas

  # computer vision
  - opencv

  # pytorch + CUDA
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  # install spacenet + ml_tools via pip
  - pip
